# Generated by Django 5.1 on 2024-09-02 04:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(blank=True, max_length=255, null=True)),
                ('complaint_raised_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint_id', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('custom_company', models.CharField(blank=True, max_length=255, null=True)),
                ('site_name', models.CharField(max_length=255)),
                ('custom_site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attended_by', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Update', 'Update')], default='Pending', max_length=10)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('claim_type', models.CharField(choices=[('Under Warranty', 'Under Warranty'), ('Chargeable', 'Chargeable')], max_length=20)),
                ('nature_of_complaint', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('location', models.CharField(default='Hyderabad', max_length=50)),
                ('custom_location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('summary_of_action_taken', models.TextField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('preventive_action', models.TextField(blank=True, null=True)),
                ('parts_replaced_for_rectification', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
