# Generated by Django 5.0.3 on 2024-10-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_complaintsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='images',
            field=models.TextField(null=True),
        ),
    ]
