# Generated by Django 5.0.3 on 2024-09-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_alter_complaint_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='custom_company',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='custom_location',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='custom_site_name',
        ),
    ]
