# Generated by Django 5.0.3 on 2024-10-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_alter_complaint_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaintsystem',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
