# Generated by Django 5.0.3 on 2024-09-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_remove_complaint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
