# Generated by Django 5.0.3 on 2024-11-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0007_alter_complaint_complaint_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
