# Generated by Django 5.0.3 on 2024-11-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0008_remove_complaint_serial_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='pdf_upload',
            new_name='pdf_file',
        ),
    ]
