# Generated by Django 5.0.3 on 2024-11-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0009_rename_pdf_upload_complaint_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('last_serial_number', models.IntegerField(default=0)),
            ],
        ),
    ]
