# Generated by Django 5.0.3 on 2024-11-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0012_delete_complaintcounter_alter_complaint_claim_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
