# Generated by Django 5.0.3 on 2024-11-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0013_complaint_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
