# Generated by Django 5.0.3 on 2025-01-04 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0015_yearlyserialnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YearlySerialNumber',
        ),
    ]
