# Generated by Django 5.2.4 on 2025-08-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0017_alter_complaint_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.CharField(default='Hyderabad', max_length=300),
        ),
    ]
