# Generated by Django 5.1.6 on 2025-09-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0018_alter_complaint_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_no', models.CharField(blank=True, max_length=50, null=True)),
                ('revision_no', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_no', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
