# Generated by Django 5.1.6 on 2025-09-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0019_complaintmeta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComplaintMeta',
        ),
    ]
