# Generated by Django 5.1.6 on 2025-09-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0021_complaintmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintmeta',
            name='issue_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
