# Generated by Django 5.1.6 on 2025-09-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0023_alter_complaintmeta_issue_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintmeta',
            old_name='issue_data',
            new_name='issue_date',
        ),
    ]
