# Generated by Django 5.0.3 on 2025-09-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0024_rename_issue_data_complaintmeta_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmeta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
