# Generated by Django 5.2.4 on 2025-07-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('MMS', 'MMS'), ('SPV', 'SPV'), ('String Cable', 'String Cable'), ('SMB', 'SMB'), ('MCS', 'MCS'), ('ACPC', 'ACPC'), ('LTC', 'LTC'), ('INV', 'INV'), ('TRAFO', 'TRAFO'), ('VCB', 'VCB'), ('HTP', 'HTP'), ('LTP', 'LTP'), ('UPS', 'UPS'), ('Battery Charger', 'Battery Charger'), ('Battery Bank', 'Battery Bank'), ('Street Light', 'Street Light'), ('LA', 'LA'), ('EP', 'EP'), ('FSS', 'FSS'), ('Metering Yard', 'Metering Yard'), ('OHL', 'OHL'), ('BE', 'BE'), ('House Keeping', 'House Keeping')], max_length=50)),
                ('checkpoint', models.TextField()),
                ('frequency', models.CharField(max_length=50)),
            ],
        ),
    ]
