# Generated by Django 5.2.4 on 2025-07-23 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=100)),
                ('project_location', models.CharField(max_length=100)),
                ('date_of_submission', models.DateField(auto_now_add=True)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('next_inspection_date', models.DateField(blank=True, null=True)),
                ('period_of_inspection', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistResponseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.checklistitem')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.checklistresponse')),
            ],
        ),
    ]
