# Generated by Django 5.2.4 on 2025-07-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_checklistresponse_image1_checklistresponse_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresponse',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
