# Generated by Django 5.2.4 on 2025-07-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_checklistresponse_signature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistresponse',
            old_name='user_image',
            new_name='image_photo',
        ),
    ]
