# Generated by Django 5.2.4 on 2025-07-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_rename_user_image_checklistresponse_image_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresponse',
            name='comments',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
