# Generated by Django 5.2.4 on 2025-07-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_checklistresponse_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresponse',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
