# Generated by Django 5.2.4 on 2025-07-23 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_checklistresponse_receiver_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistresponse',
            name='receiver_email',
        ),
        migrations.RemoveField(
            model_name='checklistresponse',
            name='sender_email',
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='Date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='make',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='rating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='s_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='typee',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='checklistresponse',
            name='period_of_inspection',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half Yearly', 'Half Yearly'), ('Annually', 'Annually')], max_length=50),
        ),
    ]
