# Generated by Django 5.2.4 on 2025-07-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_remove_checklistresponse_receiver_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistresponse',
            name='s_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
