# Generated by Django 5.2.4 on 2025-07-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_checklistresponse_image5_checklistresponse_image6'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresponse',
            name='is_draft',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
