# Generated by Django 5.2.4 on 2025-07-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_checklistresponse_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresponse',
            name='webcam_image',
            field=models.ImageField(blank=True, null=True, upload_to='webcam_photos/'),
        ),
    ]
