# Generated by Django 5.2.4 on 2025-07-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_checklistresponse_webcam_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresponse',
            name='signature_pad_data',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
