# Generated by Django 5.2.4 on 2025-07-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_checklistresponse_signature_pad_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='report_type',
            field=models.CharField(choices=[('Module Mounting Structure', 'MMS'), ('SPV', 'SPV'), ('String Cable', 'String Cable'), ('SMB', 'SMB'), ('MCS', 'MCS'), ('ACPC', 'ACPC'), ('LTC', 'LTC'), ('INV', 'INV'), ('TRAFO', 'TRAFO'), ('VCB', 'VCB'), ('HTP', 'HTP'), ('LTP', 'LTP'), ('UPS', 'UPS'), ('Battery Charger', 'Battery Charger'), ('Battery Bank', 'Battery Bank'), ('Street Light', 'Street Light'), ('LA', 'LA'), ('EP', 'EP'), ('FSS', 'FSS'), ('Metering Yard', 'Metering Yard'), ('OHL', 'OHL'), ('BE', 'BE'), ('House Keeping', 'House Keeping')], max_length=50),
        ),
    ]
