# Generated by Django 5.2.4 on 2025-07-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_checklistresponse_email_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='frequency_level',
            field=models.IntegerField(choices=[(1, 'Weekly'), (2, 'Monthly'), (3, 'Quarterly'), (4, 'Half Yearly'), (5, 'Annually')], default=1),
        ),
    ]
