# Generated by Django 5.2.4 on 2025-07-29 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_checklistitem_frequency_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(upload_to='checklist_pdfs/')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.checklistresponse')),
            ],
        ),
    ]
