# Generated by Django 5.2.4 on 2025-07-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_checklisthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='frequency',
        ),
    ]
