# Generated by Django 5.2.4 on 2025-07-31 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0021_alter_checklistitem_report_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistresponse',
            old_name='typee',
            new_name='Type',
        ),
    ]
