# Generated by Django 5.2.4 on 2025-07-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0022_rename_typee_checklistresponse_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistresponseitem',
            name='remark',
            field=models.CharField(max_length=20),
        ),
    ]
