# Generated by Django 5.2.4 on 2025-08-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0023_alter_checklistresponseitem_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistresponse',
            old_name='image_photo',
            new_name='signature1',
        ),
        migrations.RemoveField(
            model_name='checklistresponse',
            name='webcam_image',
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='signature_pad_data1',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
