# Generated by Django 5.2.4 on 2025-08-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0024_rename_image_photo_checklistresponse_signature1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='report_type',
            field=models.CharField(choices=[('Module Mounting Structure', 'MMS'), ('Solar PV (SPV)', 'SPV'), ('String Cable', 'String Cable'), ('String Monitoring Box (SMB)', 'SMB'), ('Module Cleaning System (MCS)', 'MCS'), ('Power/HT Cables AC (ACPC)', 'ACPC'), ('LT Cables AC (LTC)', 'LTC'), ('Inverter (INV)', 'INV'), ('Transformer (TRAFO)', 'TRAFO'), ('VCB', 'VCB'), ('HT Panel (HTP)', 'HTP'), ('LT Panel (LTP)', 'LTP'), ('UPS', 'UPS'), ('Battery Charger', 'Battery Charger'), ('Battery Bank', 'Battery Bank'), ('Street Light', 'Street Light'), ('Lightning Arrester (LA)', 'LA'), ('Earthpit (EP)', 'EP'), ('Fire & Safety System (FSS)', 'FSS'), ('Metering Yard', 'Metering Yard'), ('OH Line (OHL)', 'OHL'), ('Bay Extension (BE)', 'BE'), ('House Keeping', 'House Keeping')], max_length=50),
        ),
    ]
