# Generated by Django 5.2.4 on 2025-08-04 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0026_alter_checklistitem_report_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistresponse',
            name='Date',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='Date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
