# Generated by Django 5.2.4 on 2025-08-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0027_remove_checklistresponse_date_checklistitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresponse',
            name='customer_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='solon_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
