# Generated by Django 5.0.3 on 2025-08-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0028_checklistresponse_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistresponse',
            name='period_of_inspection',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half Yearly', 'Half Yearly'), ('Annually', 'Annually')], max_length=50),
        ),
    ]
