# Generated by Django 5.0.3 on 2025-08-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0029_alter_checklistresponse_period_of_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='frequency_level',
            field=models.IntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Quarterly'), (5, 'Half Yearly'), (6, 'Annually')], default=0),
        ),
    ]
