# Generated by Django 5.0.3 on 2025-08-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0030_alter_checklistitem_frequency_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='frequency_level',
            field=models.IntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Quarterly'), (5, 'Half Yearly'), (6, 'Annually')], default=1),
        ),
    ]
