# Generated by Django 5.0.3 on 2025-12-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0032_alter_checklistitem_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistresponseitem',
            name='remark',
            field=models.CharField(max_length=100),
        ),
    ]
