# Generated by Django 5.0.3 on 2025-12-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0034_checklistresponse_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresponse',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
