# Generated by Django 5.0.3 on 2025-12-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0035_checklistresponse_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistresponse',
            name='Type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checklistresponse',
            name='comments',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='checklistresponse',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checklistresponse',
            name='make',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checklistresponse',
            name='project_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='checklistresponse',
            name='project_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='checklistresponse',
            name='rating',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checklistresponse',
            name='report_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checklistresponse',
            name='s_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checklistresponse',
            name='solon_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checklistresponseitem',
            name='remark',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='checklistresponseitem',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
