# Generated by Django 5.1.6 on 2025-04-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_alter_notification_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='unit_value',
            field=models.FloatField(default=0),
        ),
    ]
