# Generated by Django 5.1.6 on 2025-04-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_inventory_unit_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='unit_value',
            field=models.FloatField(default=0),
        ),
    ]
