# Generated by Django 5.1.6 on 2025-04-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_notification_unit_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='uom',
            field=models.CharField(default="No's", max_length=50),
        ),
    ]
