# Generated by Django 5.1.6 on 2025-04-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_notification_material_desc_notification_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimenotification',
            name='material_desc',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='realtimenotification',
            name='uom',
            field=models.CharField(default="No's", max_length=50),
        ),
    ]
