# Generated by Django 5.0.3 on 2025-08-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_realtimenotification_material_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='fixed_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
