# Generated by Django 5.1.6 on 2025-08-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_inventory_fixed_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='invar',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
