# Generated by Django 5.1.6 on 2025-08-26 07:09

import Inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_inventory_invar'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='fixed_stock_year',
            field=models.IntegerField(default=Inventory.models.current_year),
        ),
    ]
