# Generated by Django 5.1.6 on 2025-08-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_inventory_fixed_stock_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='fixed_stock_year',
        ),
    ]
