# Generated by Django 5.0.3 on 2024-10-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_plant', models.CharField(max_length=100)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_company_name', models.CharField(max_length=100)),
                ('purpose_of_visit', models.CharField(max_length=255)),
                ('valid_from_datetime', models.DateTimeField()),
                ('valid_to_datetime', models.DateTimeField()),
                ('contact_details', models.CharField(max_length=255)),
                ('emergency_contact_details', models.CharField(max_length=255)),
                ('emergency_mobile_contact', models.CharField(max_length=15)),
                ('relationship', models.CharField(max_length=100)),
                ('gate_pass_issue_datetime', models.DateTimeField()),
                ('visitor_image', models.ImageField(blank=True, null=True, upload_to='visitor_images/')),
            ],
        ),
    ]
