# Generated by Django 5.0.3 on 2024-11-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0002_visitorlog_created_at_visitorlog_gatepass_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
