# Generated by Django 5.0.3 on 2024-11-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0003_alter_visitorlog_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='dup_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
