# Generated by Django 5.0.3 on 2025-02-24 04:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0004_visitorlog_dup_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='valid_from_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='valid_to_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
