# Generated by Django 5.1.6 on 2025-04-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0005_alter_visitorlog_valid_from_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='valid_from_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='valid_to_datetime',
            field=models.DateTimeField(),
        ),
    ]
